### ISSUE TITLE
'project/static/tfmodel/resnet50_model.json'

### ISSUE THREAD

**Issue by benwaldner** [conlamon/satellite-classification-flask-api#1]
The file 'project/static/tfmodel/resnet50_model.json' is missing. Or I did something wrong.

**Comment by conlamon** [comment]
Great question. Yes the model is missing, as GitHub does not like large files, so I do not upload the model files as part of the repo. If you would like the model, you can download the full "tfmodel" folder from this link: 
http://bit.ly/2HFLYQG

Just place the unzipped folder in 'project/static'. It has the .json graph file, the .hdf5 weights file and a classes.txt file. Just an FYI, this model is not the best, as the dataset has a large class imbalance, and was not trained in a way to best handle this imbalance. Hopefully it helps you figure out how to use the rest of the project though! 

I will close this issue, but let me know if something does not work out.
